import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'
import {Header, Services, BoldApproach, CriticalThinking, Testimonial, Counter, Methods, Form, Footer} from '../components'

export default function Index() {
  return (
    <div>
      <Head>
        <title>Unlimited Touch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <section className='smooth-scroll'>
        <Header className='h-screen'/>
      </section>

      {/* Services */}
      <section className='smooth-scroll'>
        <Services className='h-screen'/>
      </section>

      {/* Bold Approach */}
      <section>
        <BoldApproach/>
      </section>
      
      {/* Critical Thinking */}
      <section>
        <CriticalThinking/>
      </section>

      {/* Testimonial */}
      <section>
        <Testimonial/>
        <Counter/>
      </section>

      {/* Methods */}
      <section>
        <Methods/>
      </section>

      {/* Form */}
      <section>
        <Form/>
      </section>

      {/* Footer */}
      <section>
        <Footer/>
      </section>


        
    </div>
  )
}
